### ISSUE TITLE
Conditional CI execution for Stout

### ISSUE THREAD

**Issue by valentinfernandez1** [paritytech/trappist#200]
I've been noticing that building both trappist and stout in the CI can take a lot of time and a most of the currently ongoing changes don't really involve Stout. Would it make sense to execute this build only if the changes in a PR includes files that involve this runtime?

This paths would be `./node`, `./primitives/xcm`, and `./runtime/stout`.

There seems to be a [tool](https://github.com/dorny/paths-filter) that allows the CI to filter the changes to conditionally run commands. The solution would look something like this:
```yml
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          node:
            - 'node/**'
          stout:
            - 'runtime/stout/**'
          primitives:
            - 'primitives/**'
            - 
    # run if changes involves stout
    - name: e2e tests
      if: steps.filter.outputs.node == 'true' || steps.filter.outputs.stout == 'true' || steps.filter.outputs.primitives == 'true'
      run: |
          SKIP_WASM_BUILD=1 cargo check --release --locked --no-default-features --features with-stout-runtime
```
