### ISSUE TITLE
Update references from statemint-local to asset-hub-rococo-local on zombinet configuration files

### ISSUE THREAD

**Issue by weezy20** [paritytech/trappist#327]
For local trappist playground example [here](https://github.com/paritytech/trappist/blob/9e39a7eef41a84eae22c05ed56f5edd7298e4bde/zombienet/trappist_rococo.toml#L33) and among other configs under `trappist/zombienet` the local asset-hub parachain uses `statemint-local` as the chainspec which now would just point to [`asset-hub-polkadot`](https://github.com/paritytech/polkadot-sdk/blob/d288c81b968d9d375168eb2a0dde68b1f6ebc8a8/cumulus/polkadot-parachain/src/command.rs#L97) invalidating the assumption for a user playing with a fresh _local_ asset-hub parachain. 

`chain` would need to be updated to use `asset-hub-rococo-local` instead
```toml
[[parachains]]
id = 1000
add_to_genesis = true
cumulus_based = true
chain = "statemine-local"
```
